# Generated by Django 2.1.2 on 2020-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100, null=True)),
                ('Items_Count', models.IntegerField(blank=True, default=0, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
