# Generated by Django 2.1.2 on 2020-07-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBAV_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Item_Cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
