# Generated by Django 2.1.2 on 2020-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBAV_App', '0002_items_item_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Items_Count',
            new_name='Items_In_Stock',
        ),
        migrations.AddField(
            model_name='items',
            name='Items_Out_Stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
