# Generated by Django 4.0 on 2021-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Marks', models.IntegerField(default=0)),
            ],
        ),
    ]
